### ISSUE TITLE
The Geo-IP Map is not working

### ISSUE THREAD

**Issue by SharDX** [epsylon/ufonet#11]
is it only me or its  a major bug ?

**Comment by epsylon** [comment]
I think it is related with OS implementations (Kali, etc) of some python libs, but I am not sure at all. 
On other boxes UFONet map is working like a charm.
Btw, I am trying to fix some common problems on next release and this "bug" as you said was reported ofently. 
Actually ufonet is trying to connect to a couple of mirrors to fetch GeoIP.dat database.  
Some users (mostly Kali Linux users) have reported that they haven't that files on folder so they recieve a message similar to: "you should install python-geoip lib" when launching map. 
So first question is: Do you have that files correctly donwloaded?.
After launch first time map, you should have a folder called: **maps** on your ufonet folder.
That folder also should have 2 files: **GeoIPASNum.dat** and **GeoLiteCity.dat**
Are that files on your system?
If not; download this .tar.gz from one of that mirrors:

-    geo_db_mirror1 = 'http://176.28.23.46/bordercheck/maps.tar.gz'  
-    geo_db_mirror2 = 'http://83.163.232.95/bordercheck/maps.tar.gz' 

Extract it and place on correct way... re-launch ufonet --gui and this should works!
Also, try to create a map with a couple of zombies... because of how is made... it is searching for geoIp at the end of whole task so sometimes with huge list of zombies people doesn't wait enought time to complete processes and simply things that map is not working correctly. It is, but takes time... ;-)
I am designing new ufonet website to have a FAQ/suggestions section so will be more easy to search for "major problems".
Thanks for your report!
Cheers.

**Comment by epsylon** [comment]
check new release: v0.7 (Big Crunch) to see if this error is fixed on it...

**Comment by SharDX** [comment]
Thanks gonna test it now

and yeah iam using kali

**Comment by SharDX** [comment]
WHen i open the 'Generate map' it show
0/1700

:(

**Comment by epsylon** [comment]
Exactly, something wrong when downloading required map dbs. 
Try what I explained you before...
1. download: http://176.28.23.46/bordercheck/maps.tar.gz
2. extract it (this generates a folder called 'maps' with 2 files in.
3. place that folder on ufonet's root path

**Comment by diegopenhap** [comment]
NO FUNCIONA ESTA UFONET,  NO HACE NI COSQUILLAS A LAS WEBS, MAL TRABAJO.

**Comment by azamet90** [comment]
[Error] [AI] Cannot import lib: pygeoip. 

 To install it try:

 $ 'sudo apt-get install python-geoip' or 'pip install geoip'

^C ⚙ azamet@MrRobots  ~/.../cehennem/ufonet   master ●  ^C
 ✘⚙ azamet@MrRobots  ~/.../cehennem/ufonet   master ●  sudo pip install geoip
Requirement already satisfied: geoip in /usr/local/lib/python3.7/dist-packages (1.3.2)

**Comment by Godtier37** [comment]
I wonder if he just made it so linux machines get RATTS instead of the actual thing as ufonet for linux is done for. Whats the deal are you RATTING for a while then gonna magically make an update that fixes it when people clock. Or are unable to fix it for linux users.
