### ISSUE TITLE
LOIC / LORIS Questions

### ISSUE THREAD

**Issue by DeaDHackS** [epsylon/ufonet#112]
Hello! I do scripts and i'm working on Paladin which is a tool which has a lot of the best DoS / DDoS tools!
UFONet is include but i wanna to modify the LOIC and LORIC .py scripts if thats alright to make my own dos tool, if thats okay of course.

I tried using it doing like python loic.py target port etc doesn't work...

So how can i use them both? Without UFONet, if thats okay of course. LOIC is not on linux with exepct mono so its why i'm asking ;D

Lots of love!
AND THANKS FOR MAKING UFONet!

**Comment by trollmad3** [comment]
By LOIC you mean Low Orbit Ion Cannon correct?

**Comment by trollmad3** [comment]
@DeaDHackS It is opensource so sure. Just make sure to give me credit.

**Comment by DeaDHackS** [comment]
Ahaha great but know anyway how i can use loic.py scripts?

**Comment by trollmad3** [comment]
@DeaDHackS No sorry. I stopped using UFOnet a long time ago.

**Comment by DeaDHackS** [comment]
Ah damm ;c at least can you give me a favor? Since you code in python (i assume) can you modify the loic.py and loic.pyc file for it to work with aguerements like:
python loic.py target port 
Please? I can't code in python i'm really bad at it. I'm good with bash ;D but i can't do a dos script with bash without using another tool.

**Comment by epsylon** [comment]
@trollmad3 remember: open source != free software
UFONet is free software (GPLv3) so you can modify code as you wish.
@DeaDHackS you can take both scripts loris.py and loic.py and try to build a __main__ to be launched as single scripts, easily. By the way, you also need to know how to add also proxies, because UFONet has introduced that to those DoS scripts. 
Obviously I will not make you that task. But you have also nice similar scripts here on GitHub, more related on the way to be executed as you want: <ip> <port>. Try also to check them.

**Comment by DeaDHackS** [comment]
Umm sorry psy but i'm bad at python..i don't code in python....only in bash :( sadly. But yeah between there is a bug with UFONet doesn't load my zombie map and sometimes says '[error] something went wrong.' While searching for zombies..

**Comment by trollmad3** [comment]
@epsylon He was asking if he can use my  [Python Password Generator](https://github.com/trollmad3/Python-Password-Generator) on my github.

**Comment by epsylon** [comment]
@trollmad3 I didn't see that question..btw, okz..

**Comment by DeaDHackS** [comment]
I finally created my botnet ;D which uses a python backdoor..
