### ISSUE TITLE
error: can't start new thread

### ISSUE THREAD

**Issue by Mineez** [epsylon/ufonet#128]
Hi, i am experiencing this "glitch" when i am starting an attack or testing the botnet. Here is the full error =) I know that this glitch has been already reported but i couldn't find a working solution. 
Cordially, Mineez

( sorry for my english ^^) 

Traceback (most recent call last):
  File "/root/ufonet/core/main.py", line 769, in run
    test = self.testing(zombies)
  File "/root/ufonet/core/main.py", line 2842, in testing
    reply = self.connect_zombies(zombie)
  File "/root/ufonet/core/main.py", line 970, in connect_zombies
    t.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
>>> 

[Error] - Something wrong testing!

**Comment by epsylon** [comment]
Hi, 
@Mineez yes, this "glitch" has been (mostly) explained, for example, here: https://github.com/epsylon/ufonet/issues/47#issuecomment-266882658 
Are you using Kali Linux?. Which version? 
I think that there is something not correctly implemented there, because on a Debian (sid) with 200 threads and ~1000 zombies I am not having it...
Please, try to reduce/manage this options:
  - threads
  - delay
  - retries
  - nº of zombies
Playing a bit with that parameters, you will make more easy for you OS to open/close threads.
