### ISSUE TITLE
ERROR:zygota_host_impl_linux.cc

### ISSUE THREAD

**Issue by sunil2985** [epsylon/ufonet#129]
Hi i am gettin error while running ufonet --gui --> zygota_host_impl_linux.cc
Ruuning as root without --no-sandbox
How to fix this???

**Comment by epsylon** [comment]
This looks like a problem related with your Chromium web browser and the function to auto-launch it when gui is started from shell:
https://github.com/adobe/chromium/blob/master/content/browser/zygote_host_impl_linux.cc
You can try to install other browser. Or, you can open your Chromium browser first, launch UFONet for gui, and enter manually on the url this one: http://127.0.0.1:9999

**Comment by sunil2985** [comment]
Thanks Mate!! 💯 
Funny thing is i dont have chromium installed on by linux :)

**Comment by epsylon** [comment]
Lol! ;-)
We are calling to open GUI a function named 'open' from a python lib called 'webbrowser'. Supodesly it tries to open your default browser or, a new tab on a browser that you have open previously. Maybe you had installed chromium and some confs are still poiting to that app. Try to 'purge' it from your system, because the reference that you provide here shows that is still working.
