### ISSUE TITLE
[Error] - Something wrong attacking!

### ISSUE THREAD

**Issue by IlTuoNome** [epsylon/ufonet#135]
Hi, I often get the following error during an attack test:

[Error] - Something wrong attacking!
Traceback (most recent call last):
  File "/root/extra/Tools/ufonet/core/main.py", line 815, in run
    attack = self.attacking(zombies)
  File "/root/extra/Tools/ufonet/core/main.py", line 3006, in attacking
    reply = self.injection(target, zombies)
  File "/root/extra/Tools/ufonet/core/main.py", line 3284, in injection
    self.herd.dump_html()
  File "/root/extra/Tools/ufonet/core/herd.py", line 115, in dump_html
    out=self.get_stat()
  File "/root/extra/Tools/ufonet/core/herd.py", line 220, in get_stat
    if self.connection[zombie_stat]:
KeyError: 'http://site.com/default.asp?pageurl='

Tested through the latest version of ufonet and kali linux.

**Comment by trollmad3** [comment]
Can you run the same attack you did but add `-v` to it, then post the results in here?

**Comment by IlTuoNome** [comment]
I noticed that this error happens to me when the round is more than 1.

[Info] Payload: http://www.site.com/discipline.php?type=http://site.com
[Response] code:  200  time  0.359465  size  13485
[Info] Payload:http://www.site.com/user/login?redirect=http://site.com
[Response] code:  200  time  0.30887  size  14141
[Info] Payload: http://www.site.com/login/?URL_GO=http://site.com
[Response] code:  200  time  0.300974  size  24314
[Info] Payload:http://www.site.com/intranet/login.php?redirect=http://site.com
[Response] code:  200  time  0.075783  size  12551
[Info] Payload: http://www.site.com/login?redirect=http://site.com
[Response] code:  200  time  0.100667  size  706
[Info] Payload:http://www.site.com/Account/LogOn?ReturnUrl=http://site.com
[Response] code:  200  time  0.147253  size  34373
[Info] Payload: http://www.site.com/user/login?url=http://site.com
[Response] code:  200  time  0.3817  size  29589
[Response] code:  200  time  0.193345  size  4748
[Response] code:  200  time  0.260118  size  21812
[Control] Active zombies: 1 , waiting for them to return...
[Control] Active zombies: 1 , waiting for them to return...
[Response] code:  200  time  2.767021  size  2831


[Control] All zombies returned to the master ;-)




[Info] Scanning target to check for levels on defensive shields...

 -Total tests: 2 

   -Bytes in (first round)    : 8.67 KB
   -Bytes in (this round)     : 8.67 KB
   -Bytes in (median)         : 8.67 KB

   -Load time (first round)   : 0.56 seconds
   -Load time (this round)    : 0.55 seconds
   -Load time (median)        : 0.555 seconds 

[Info] SCANNER: Your target is loading this round faster than the previous one... o_0



[Error] - Something wrong attacking!

Traceback (most recent call last):
  File "/root/extra/Tools/ufonet/core/main.py", line 815, in run
    attack = self.attacking(zombies)
  File "/root/extra/Tools/ufonet/core/main.py", line 3006, in attacking
    reply = self.injection(target, zombies)
  File "/root/extra/Tools/ufonet/core/main.py", line 3284, in injection
    self.herd.dump_html()
  File "/root/extra/Tools/ufonet/core/herd.py", line 115, in dump_html
    out=self.get_stat()
  File "/root/extra/Tools/ufonet/core/herd.py", line 220, in get_stat
    if self.connection[zombie_stat]:
KeyError: 'http://www.site.com/Event.html?currentPage='
[Response] code:  200  time  4.221666  size  29017

**Comment by epsylon** [comment]
Looks that something goes wrong when generating final stats for some zombies. 
Can you try to remove this zombie from your list:
-> KeyError: 'http://www.site.com/Event.html?currentPage='
And try it again?.
 Which command are you using to execute the tool (are you using LOIC, LORIS,  UFOSYN..)

**Comment by epsylon** [comment]
-> I noticed that this error happens to me when the round is more than 1.
I will check this.

**Comment by IlTuoNome** [comment]
I use this command:  ./ufonet --no-head --no-aliens --no-droids --no-ucavs --no-rpcs -r 2 -a TARGETEST

In my tests I no longer get the error I had reported but now at the end of the various rounds in loop I get this message: [Control] All zombies returned to the master ;-)
[Response] code:  200  time  0.35904  size  29965
[Response] code:  200  time  0.252931  size  27124
[Response] code:  200  time  0.278851  size  3749
[Control] Active zombies: 2 , waiting for them to return...
[Response] code:  200  time  0.220103  size  6138
[Response] code:  200  time  0.433238  size  8875

[Control] All zombies returned to the master ;-)
[Control] All zombies returned to the master ;-)
[Control] All zombies returned to the master ;-)
[Control] All zombies returned to the master ;-)
[Control] All zombies returned to the master ;-)
[Control] All zombies returned to the master ;-)
[Control] All zombies returned to the master ;-)
[Control] All zombies returned to the master ;-)
…….

To stop this I have to press CTRL + C.
It only happens when the round is greater than 1.

**Comment by epsylon** [comment]
Well. I have checked it and it is working, almost using default zombies list:
./ufonet -a http://host.net -r 3 -v
[...]
[Info] Scanning target to check for levels on defensive shields...

 -Total tests: 3 

   -Bytes in (first round)    : 29.0 KB
   -Bytes in (previous round) : 29.11 KB
   -Bytes in (this round)     : 29.0 KB
   -Bytes in (max)            : 29.11 KB
   -Bytes in (min)            : 29.0 KB
   -Bytes in (median)         : 29.0 KB
 ----
   -Load time (first round)   : 8.70 seconds
   -Load time (previous round): 7.96 seconds
   -Load time (this round)    : 8.80 seconds
   -Load time (max)           : 8.80 seconds
   -Load time (min)           : 7.96 seconds
   -Load time (median)        : 8.7 seconds 

[Info] SCANNER: Your target is serving content more slowly this round... [Keep shooting!]
Total invocations: 3 | Zombies: 1 | Hits: 0 | Fails: 3
Total time: 0:00:16.543825 | Avg time: 0:00:05.514608
Total size: 0.0B | Avg size: 0.0B
---------------------
==========================================
Troops statistics
==========================================
Aliens: 2 | Hits: 6 | Fails: 0
Droids: 1 | Hits: 3 | Fails: 0
UCAVs : 3 | Hits: 6 | Fails: 3
XRPCs : 1 | Hits: 2 | Fails: 1
[...]
That means that probably is related with your specific list of zombies. Btw, it looks like an issue to be solves, because this shouldn't be like this. 
Is that zombie failing and noticed as a traceback still online?:
-> KeyError: 'http://www.site.com/Event.html?currentPage='

**Comment by epsylon** [comment]
I am thinking into add on the new code release a kind of "dynamic requests per zombie" system, which can try to automatically reconfigure some parameters trying to be more adaptative for the requeriments of each specific zombie. That's interesting because some are more faster than others and that can produce even problems with threading system, when a thread needs to complete all requeriments (retries, delays..). At some point and which so much rounds launched I have experimented some glitches at this way. This will probably fix this kind of issue, for example, hot-discarding those zombies that aren't replying to some conf by user need. Ex: I only want zombies that replies in less than 3 secs, etc..

**Comment by IlTuoNome** [comment]
I tried to use this command: ./ufonet --no-head --no-aliens --no-droids --no-ucavs --no-rpcs -r 2 -a TARGETEST  --timeout=1 --delay=1 --retries=1
but nothing keeps telling me:
[Control] All zombies returned to the master ;-)
[Control] All zombies returned to the master ;-)
[Control] All zombies returned to the master ;-)
[Control] All zombies returned to the master ;-)
[Control] All zombies returned to the master ;-)
[Control] All zombies returned to the master ;-)
[Control] All zombies returned to the master ;-)
[Control] All zombies returned to the master ;-)
[Control] All zombies returned to the master ;-)
…...
By checking with wireshark while the program tells me: [Control] All zombies… no type of web request is forwarded.

**Comment by epsylon** [comment]
Ok. I see. That message is more related with the internal workers of the threading system (not about web requests). For some reason, if you are telling me that you have waited for some time searching for an end but you are getting into a loop, somethings goes wrong when trying to close open threads. Kali Linux common implementations are actualy experimenting some issues related on how python/threads are working, almost when using UFONet. Can you try (just for testing tasks) to reduce your list of zombies. Le'ts try it with 5 of each and see whats happen.

**Comment by epsylon** [comment]
And if you want to spell this:  ./ufonet --no-head --no-aliens --no-droids --no-ucavs --no-rpcs -r 2 -a TARGETEST --timeout=1 --delay=1 --retries=1
Just try to reduce your "zombies.txt" list to 5. Let's see if that loop happens.

**Comment by IlTuoNome** [comment]
I tried to reduce the sites of the file Zombies.txt to 10 but nothing, to 5 nothing and to finish at 1 but always returns me the same message.

**Comment by epsylon** [comment]
Ok, so let's try it but making changes in other places. For example, let's check if --threads are ok. Try to increase --threads to 200. If isn't working, try to reduce them to 1.

**Comment by epsylon** [comment]
Another question. Which python version are you using?

**Comment by IlTuoNome** [comment]
Trying back with the thread at 1 returned the KeyError error: 'http://www.site.com/user/login?url=' indicating a different site from the previous one, I checked and the site is online and working.

**Comment by epsylon** [comment]
->  while with --threads = 1 seems to go
Looks that a problem on how threads are managed by your python/OS.

**Comment by IlTuoNome** [comment]
What system can I use to make it work properly?

**Comment by epsylon** [comment]
I can tell you my experience. I have made test with Gentoo, Arch and Debian (sid + stretch) and I haven't on any moment these errors related with threading/OS. I will try to check for another way to manage "internal workers", when Kali (and similars, ParrotOS, etc) are running the tool. But, btm, I cannot provide you a specific fix for your issue. Just try to decrease threading..

**Comment by IlTuoNome** [comment]
I will try to test it on different systems, I will keep you updated.

**Comment by epsylon** [comment]
Many thanks, even for your patient making test.

**Comment by IlTuoNome** [comment]
I'm trying to install Ufonet on Ubuntu mate downloaded via git clone, but in the installation I have this problem:
Installed /usr/local/lib/python2.7/dist-packages/ufonet-1.1-py2.7.egg
Processing dependencies for ufonet==1.1
Searching for python-scapy>=2.3.3
Reading https://pypi.python.org/simple/python-scapy/
Couldn't find index page for 'python-scapy' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or working download links found for python-scapy>=2.3.3
error: Could not find suitable distribution for Requirement.parse('python-scapy>=2.3.3')

**Comment by epsylon** [comment]
From here: https://ufonet.03c8.net/#installation
For manual installation on Debian-based systems (ex: Ubuntu), run: 
sudo apt-get install python-pycurl python-geoip python-whois python-crypto python-requests python-scapy
Btw, you have reason, there is a problem on requirements, because package is called "scapy", and not "python-scapy". I will make a commit fixing that.
Thanks again.

**Comment by epsylon** [comment]
Done! -> https://github.com/epsylon/ufonet/commit/9c5e267c608f5739769405b1a4e01b789219cd1a
Please try it again running new setup.py
Ex: python setup.py install

**Comment by epsylon** [comment]
+info: https://pypi.org/simple/scapy/

**Comment by trollmad3** [comment]
@IlTuoNome This issue is fixed?

**Comment by epsylon** [comment]
@IlTuoNome I have added your issue on a review for next code release which is fixing this error:

Traceback (most recent call last):
File "/root/extra/Tools/ufonet/core/main.py", line 815, in run
attack = self.attacking(zombies)
File "/root/extra/Tools/ufonet/core/main.py", line 3006, in attacking
reply = self.injection(target, zombies)
File "/root/extra/Tools/ufonet/core/main.py", line 3284, in injection
self.herd.dump_html()
File "/root/extra/Tools/ufonet/core/herd.py", line 115, in dump_html
out=self.get_stat()
File "/root/extra/Tools/ufonet/core/herd.py", line 220, in get_stat
if self.connection[zombie_stat]:
KeyError: 'http://www.site.com/Event.html?currentPage='
[Response] code: 200 time 4.221666 size 29017

Please, stay tuned.
