### ISSUE TITLE
WARNING: No route found for IPv6 destination :: (no default route?)

### ISSUE THREAD

**Issue by trollmad3** [epsylon/ufonet#143]
I get this error whenever I try to attack someone via IP. I tried to see if it was websites and did `www.google.com` as an example to see if that would work. It did, so I think its an issue with targeting IP addresses. 
![virtualbox_2018-12-07_11-17-41](https://user-images.githubusercontent.com/7843719/49662563-d1708380-fa11-11e8-98c3-51c313898588.png)

**Comment by epsylon** [comment]
Hi,
Which command have you used to start your test?
Is that related with UFOSYN mod?
I said that because there is an issue related (and reported) at scapy lib:
https://github.com/secdev/scapy/issues/810
This is just a WARNING that you can ignore and of course, it is not directly related with the code of UFONet.
