### ISSUE TITLE
Add option to insert search engines

### ISSUE THREAD

**Issue by peterpt** [epsylon/ufonet#146]
By default ufonet have configured a set of search engines to crawl for webpages with specific dork request , but right now only have yahoo and bing , and there are a lot of search engines around the web that accept the same iniurl: option to search for webpages .
What about creating an option for user to add a search engine , and then ufonet will do the tests .
In case test is successful then you could add a button to send it to your home base (website) like a database .

**Comment by trollmad3** [comment]
+1 this would be very helpful.

**Comment by epsylon** [comment]
Hi,
@peterpt "there are a lot of search engines around the web that accept the same iniurl: option to search for webpages" 
Can you provide me a list of them?
Dorking systems based on regular expressions updates are we are using for UFONet, are flexible but unique to each engine, so that general solutions doesn't work as easy as sounds. For example, UFONet has some options for geo-location evasion or to try a better results based on the API of the search engine. That means that, your results from X, aren't the same that from Y. For that, we try to "hack" it more than to implement it.

**Comment by epsylon** [comment]
I will check it.

**Comment by epsylon** [comment]
Btw, remember that you can also discover UFONet zombies by using other tools. 
For example the NMap 'Open Redirect" LUA script: 'http-open-redirect' -> https://nmap.org/nsedoc/scripts/http-open-redirect.html

**Comment by epsylon** [comment]
I close this 'issue'. Maybe next time, try to add it as a Pull Request.
Thanks.

**Comment by epsylon** [comment]
Added (btm) 2 new search engines for the next UFONet release (v1.3):
 - StartPage (set by default): https://startpage.com
 - Duckduckgo: https://duckduckgo.com
