### ISSUE TITLE
Error for running any commands except for --help

### ISSUE THREAD

**Issue by ShadowWoIf** [epsylon/ufonet#156]
The following set of error has been popping up whenever I try using any commands on ufonet except for --help.

Traceback (most recent call last):
  File "./ufonet", line 16, in <module>
    app.run()
  File "/home/seed/Desktop/ufonet/core/main.py", line 291, in run
    self.start_ship_engine()
  File "/home/seed/Desktop/ufonet/core/main.py", line 275, in start_ship_engine
    self.update_flying_stats() # update flying time stats
  File "/home/seed/Desktop/ufonet/core/main.py", line 1294, in update_flying_stats
    stats_json_file = open(self.mothership_stats_file, "w+")
IOError: [Errno 13] Permission denied: 'core/json/stats.json'

I temporarily got rid of the problem by chmod -R 777 ./ on ufonet folder. If there is a proper solution, could you provide me with that?
Thanks

**Comment by epsylon** [comment]
Hi

>  IOError: [Errno 13] Permission denied: 'core/json/stats.json'

You do not need to install/run UFONet as root. When necessary, the tool will ask you to enter the credentials (for example, in several attacks using layer 3, since privileges are needed to open the socket).

Solution: Try to clone the repository again. And if not, try to change the permissions in the following way:
  - If your user is: user
  - If your path is: / ufonet

chown -R user: user ../
chmod 775 -R ../
chmod + x ufonet.py
