### ISSUE TITLE
Can not connect to zombies

### ISSUE THREAD

**Issue by cratore** [epsylon/ufonet#172]
I get this error message: [Error] [AI] [Control] From Others: No [Cannot connect!]
I this happens? Should I open a port on my router or what is the reason?

**Comment by epsylon** [comment]
That means that your external checker is failing. Can you try it again but using -v (verbose) mode?

**Comment by cratore** [comment]
I get different results testing some websites with -a http://xxxxx and additionally using -v

HTTP/1.1 403 Forbidden
Content-Type: text/html, charset=UTF-8
Connection: close
Set_Cookie: ............
domain:xxxxxxx; HttpOnly
X-Frame-Options SAMEORIGIN

HTTP/1.1 301 Moved Permanently
Server: Apache
Keep-Alive: timeout=50, max=50
Coonection: Keep-Alive
Content-Type: text/html; charset

HTTP/1.1 406 Not Acceptable
Content-Length: 1346
Content-Type: text/html
X-Powered-By: ASP.NET

There occurs always the above mentioned error.

**Comment by epsylon** [comment]
@cratore 412/5000
The errors you show below have nothing to do with the first one. They are different things.
The first refers to the fact that the external checker you use has failed to reach your target. This may be due to several reasons, even if it was not available when you used it.
The second has to do with the HTTP information that zombies return to you when they try to access your target. What can be seen is that they do not work properly. You must update your list of zombies or look for new ones that work.
