### ISSUE TITLE
auto-search error

### ISSUE THREAD

**Issue by thecyberpianist** [epsylon/ufonet#178]
![image](https://user-images.githubusercontent.com/57275785/68064058-9942f500-fcf5-11e9-8dac-7b34cad4b2fc.png)

**Comment by Aholicknight** [comment]
Repeat the same command you did but add `-v` to it and then post the results here.

**Comment by thecyberpianist** [comment]
@Aholicknight this print alredy has the -v

**Comment by Aholicknight** [comment]
@thecyberpianist Post the command you used.

**Comment by epsylon** [comment]
@thecyberpianist This can be related to many things. For example, that search engine has block you because of too many requests. Or that your connectivity has failed, etc... Btw, you should have "humans.txt" with all the "zombies" that you have found. So, when you restart this process, you will be ask to reload them. Try it this way and if stops, check for specific zombie to see if it stops at same point.
