### ISSUE TITLE
geoip error

### ISSUE THREAD

**Issue by kuklofon** [epsylon/ufonet#18]
Hi!
I use ufonet on ParrotSec. I did  sudo apt-get install python-pycurl python-geoip before use ./ufonet but still have
Error importing: pygeoip lib. 

 On Debian based systems:

 $ sudo apt-get install python-geoip
How to fix it ?

**Comment by SharDX** [comment]
Yea IAm getting the same error , need help asap

**Comment by SharDX** [comment]
@epsylon

**Comment by epsylon** [comment]
Try this: https://github.com/epsylon/ufonet/issues/11

**Comment by SharDX** [comment]
@epsylon  i downloaded and placed the map folder but still getting the error

**Comment by SharDX** [comment]
it just spam me this when i try to generate map
Error importing: pygeoip lib. 

 On Debian based systems:

 $ sudo apt-get install python-geoip


Error importing: pygeoip lib. 

 On Debian based systems:

 $ sudo apt-get install python-geoip


Error importing: pygeoip lib. 

 On Debian based systems:

 $ sudo apt-get install python-geoip

**Comment by epsylon** [comment]
@SharDX please respect others thread... 

Almost to research particulary whats going on... You have your own thread to solve this, because you are using a different system (Kali). Maybe this is not working for you but can support to @kuklofon.. So, don't be annoying. Ok? ^_^

Looks that your OS cannot found python-geoip path version (which is NOT A PROBLEM OF UFONET code!)

After do what I told you before (download maps, extract, etc...), we need to see what python ($ python --version) and python-geoip version are you using and if the path to that lib on the system is correct or not.

To have lib package version:

$ apt-cache show python-geoip

To see if paths are correctly:

$ cat /var/lib/dpkg/info/python-geoip.list

> /.
> /usr
> /usr/share
> /usr/share/doc
> /usr/share/doc/python-geoip
> /usr/share/doc/python-geoip/changelog.Debian.amd64.gz
> /usr/share/doc/python-geoip/changelog.Debian.gz
> /usr/share/doc/python-geoip/copyright
> /usr/lib
> /usr/lib/python2.7
> /usr/lib/python2.7/dist-packages
> /usr/lib/python2.7/dist-packages/GeoIP.x86_64-linux-gnu.so
> /usr/lib/python2.7/dist-packages/GeoIP-1.3.2.egg-info
> /usr/lib/python2.7/dist-packages/GeoIP-1.3.2.egg-info/top_level.txt
> /usr/lib/python2.7/dist-packages/GeoIP-1.3.2.egg-info/PKG-INFO
> /usr/lib/python2.7/dist-packages/GeoIP-1.3.2.egg-info/dependency_links.txt
> 

Do you have this file correctly located (this is on a x86_64 system)?

 _/usr/lib/python2.7/dist-packages/GeoIP.x86_64-linux-gnu.so_

**Comment by indigopsy** [comment]
same problem on backbox

**Comment by epsylon** [comment]
@indigopsy Did you tried before proposed methods to fix it?

**Comment by SharDX** [comment]
@epsylon  i have 3 oses on my laptop i like ufonet cause its easy and there aren't a lot of other alternatives , geoip map looks like a cool feature , 
i tried ufonet on kali . working without map
i tried ufonet on ubuntu 16 working without map

**Comment by SharDX** [comment]
this is the output of cat /var/lib/dpkg/info/python-geoip.list

> 

/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/python-geoip
/usr/share/doc/python-geoip/copyright
/usr/share/doc/python-geoip/changelog.Debian.gz
/usr/lib
/usr/lib/python2.7
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/GeoIP.x86_64-linux-gnu.so
/usr/lib/python2.7/dist-packages/GeoIP-1.3.2.egg-info
/usr/lib/python2.7/dist-packages/GeoIP-1.3.2.egg-info/PKG-INFO
/usr/lib/python2.7/dist-packages/GeoIP-1.3.2.egg-info/dependency_links.txt
/usr/lib/python2.7/dist-packages/GeoIP-1.3.2.egg-info/top_level.txt

>

**Comment by epsylon** [comment]
I don't speak clear or what?

@indigopsy you have an issue open here... Did you solve it?

@SharDX you also have a thread to solve your problem, here.

Btw, let's keep researching. Try this script:

> $ vim testgeoip.py

> #!/usr/bin/env python 
> # -*- coding: utf-8 -*-"
> try:
>     import pygeoip
>     print "\nLibrary correctly imported!\n"
> except:
>     print "\nError importing: pygeoip lib...\n"

> $ python testgeoip.py

Which message to do you have when executing?

**Comment by kuklofon** [comment]
#apt-cache show python-geoip
Package: python-geoip
Source: python-geoip (1.3.2-1)
Version: 1.3.2-1+b2
Installed-Size: 74
Maintainer: Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>
Architecture: amd64
Depends: geoip-database, python (<< 2.8), python (>= 2.7~), libc6 (>= 2.4), libgeoip1
Size: 19078
SHA256: b27c85611f5401ed811ff10350e190b9b06ad6fb9915946fe65a38b6e420a980
SHA1: c379177dd4cc7b9fde8e34ed697871daa251de3e
MD5sum: bf26b592aac9ef264981a7f2b6ad6f06
Description: Python bindings for the GeoIP IP-to-country resolver library
 GeoIP is a library that enables the user to find the country that any
 IP address or hostname originates from, using a database instead of
 DNS.
 .
 This package contains the Python bindings for GeoIP, allowing to use
 this library within a Python program.
Description-md5: 7728feb20ccb4df284edbff75a08cb2d
Tag: devel::lang:python, devel::library, implemented-in::python,
 role::app-data, role::devel-lib
Section: python
Priority: optional
Filename: pool/main/p/python-geoip/python-geoip_1.3.2-1+b2_amd64.deb

#cat /var/lib/dpkg/info/python-geoip.list
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/python-geoip
/usr/share/doc/python-geoip/changelog.Debian.amd64.gz
/usr/share/doc/python-geoip/changelog.Debian.gz
/usr/share/doc/python-geoip/copyright
/usr/lib
/usr/lib/python2.7
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/GeoIP.x86_64-linux-gnu.so
/usr/lib/python2.7/dist-packages/GeoIP-1.3.2.egg-info
/usr/lib/python2.7/dist-packages/GeoIP-1.3.2.egg-info/top_level.txt
/usr/lib/python2.7/dist-packages/GeoIP-1.3.2.egg-info/PKG-INFO
/usr/lib/python2.7/dist-packages/GeoIP-1.3.2.egg-info/dependency_links.txt

I placed MAPS into Ufonet directory and still have 
Error importing: pygeoip lib. 

 On Debian based systems:

 $ sudo apt-get install python-geoip

**Comment by kangdooosik** [comment]
plz. solve it problem. im using ubuntu.

**Comment by epsylon** [comment]
Welcome to github @kangdooosik. You created an account to come here... nice! :dancer: 

> "plz. solve it problem. im riding a bike"

Look guys... This visual map is just an addon for GUI to have a fancy view of your botnet, attacks, etc.. 

You can conduct DDoS attacks normally using UFONet without it, so **is not a critical issue**.

Enjoy this video and check on youtube for others.. you will see that is not a general problem: http://ufonet.03c8.net/ufonet/UFONet-v0.7.ogv

On the other hand, I need repeat it again and again.. **this issue is not related with UFONet** code. 

Is a problem on how your particular OS is configured... And is related with how many time are you spending to understand what's going on, really.. Which is 0 seconds... Why I know that?. Well...take a look to the code related with python-geoip importing problem:

https://github.com/epsylon/ufonet/blob/master/core/ajaxmap.py#L16

That's it!. :8ball: 

I can try to help you but one by one, because every OS is different... 

You can start by executing this [script provided here](https://github.com/epsylon/ufonet/issues/18#issuecomment-248271440). Is importing python-geoip correctly after run it?. 

Send me captures with results to confirm that you are not trolling this place...hehe.. or I will close this issue soon  ;-)

**Comment by kuklofon** [comment]
I solved this problem.. The reason is simple as usual. pip install pygeoip.
Add this string to the manual please.  Method works on Kali/Parrot/Arch

**Comment by epsylon** [comment]
Finally ! :+1: 
I told you. It is a problem on how OS is managing python-geoip path to lib, not a problem of UFONet code.
Thanks for try it. I am pretty sure you gonna like new release (that will be deployed soon)....

**Comment by defcon23** [comment]
this tool dont seem to have any real impact against websites , after several tests..

**Comment by epsylon** [comment]
@defcon23 this is not related with this thread... 
btw, there are many factors to have a real impact, not only related with the tool. 
should be nice to listen if you really know about what are you talking about... and of course, have more positive contributions from you than come here, a code repository, to say whats you said.

**Comment by ziflar** [comment]
hello i have the same problem ,when i have tested to import  pygeoip: i have an error
i do "pip install geoip" and the problem still exit .
the solution to resolve probleme is 
sudo pip install geoip
all is ok

**Comment by epsylon** [comment]
@ziflar thanks for your comment.

**Comment by myrondebruijn** [comment]
Turns out some Ubuntu OS'es cant implement the standard pygeoip libs from the dpkg installed packages.  U need to manually install and build those.Use these commands to fix the problem:

sudo apt-get install -y git-core
mkdir -p ~/build/pygeoip
cd ~/build/pygeoip
git clone https://github.com/appliedsec/pygeoip
cd pygeoip
sudo python setup.py install
mkdir -p ~/build/pygeoipmax
cd ~/build/pygeoipmax
wget http://www.maxmind.com/download/geoip/api/python/GeoIP-Python-latest.tar.gz
tar xvfz GeoIP-Python-latest.tar.gz
cd GeoIP-Python-*/
python setup.py build
sudo python setup.py install
mkdir -p ~/build/geoip
cd  ~/build/geoip
wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
tar vxvf GeoLiteCity.dat.gz
wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
tar vxvf GeoIP.dat.gz

**Comment by SmallHack1903** [comment]
./ kısmında hata alıyrum

**Comment by ritwickhaldar2016** [comment]
try 
sudo apt-get install python3-geoip

**Comment by trollmad3** [comment]
@kuklofon This issue was resolved on `Oct 1, 2016`

**Comment by brodyxcringe** [comment]
[Error] [AI] Cannot import lib: pygeoip.

 To install it try:

 $ 'sudo apt-get install python3-geoip libgeoip-dev libgeoip1'


[Error] [AI] Cannot import lib: pygeoip.

 To install it try:

 $ 'sudo apt-get install python3-geoip libgeoip-dev libgeoip1'

**Comment by epsylon** [comment]
@brodyxcringe -> https://ufonet.03c8.net/#installation

**Comment by HDaskalov** [comment]
> Turns out some Ubuntu OS'es cant implement the standard pygeoip libs from the dpkg installed packages. U need to manually install and build those.Use these commands to fix the problem:
> 
> sudo apt-get install -y git-core mkdir -p ~/build/pygeoip cd ~/build/pygeoip git clone https://github.com/appliedsec/pygeoip cd pygeoip sudo python setup.py install mkdir -p ~/build/pygeoipmax cd ~/build/pygeoipmax wget http://www.maxmind.com/download/geoip/api/python/GeoIP-Python-latest.tar.gz tar xvfz GeoIP-Python-latest.tar.gz cd GeoIP-Python-*/ python setup.py build sudo python setup.py install mkdir -p ~/build/geoip cd ~/build/geoip wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz tar vxvf GeoLiteCity.dat.gz wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz tar vxvf GeoIP.dat.gz

I confirm this worked as a charm on Kali Linux, dec. 2024. Old, but gold fix - thank you!
