### ISSUE TITLE
Cannot wrap my head arround the core concept

### ISSUE THREAD

**Issue by pcouy** [epsylon/ufonet#187]
Sorry if you do not consider github issues to be the right place for this, but I can't find a better place.

I have been Googling around for a few hours now, trying to understand how an Open Redirect on a website can turn this website into any kind of "Zombie" or even a proxy. Even if you were to trick a large number of people to visit an open-redirect-vulnerable page, they would only get redirected once.

Did I miss something that makes this technique work, or is this just some elaborate meme-powered-skiddie-bait ?

**Comment by epsylon** [comment]
Hi @pcouy  

> I have been Googling around for a few hours

Really? . So, you should check about if Google is a good search engine for your purposes..  :)

> trying to understand how an Open Redirect

- https://affinity-it-security.com/what-is-an-open-redirect/
- https://cwe.mitre.org/data/definitions/601.html
- https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html

> they would only get redirected once

What happens if there are thousands, or even hundreds of thousands, and they all go to the same point?. There is a denial of service, in this case, distributed, which is exactly what UFONet does.

You should check the FAQ for better information: https://ufonet.03c8.net/#docs

**Comment by pcouy** [comment]
I DO know what an open redirect is : it allows me to craft a link that appears to be hosted on some domain, but when opened in a web browser redirects to another domain. The main purpose (attacker-wise) of this class of vulnerabilities is to perform phishing attacks. In no way does it make the server (that you call a "zombie") perform any request to the target. Maybe you are mixing up "Open Redirect" and "Server Side Request Forgery", or maybe you are just plain dishonnest.

I highly suspect you of tricking script kiddies into running your software so that THEY become bots inside YOUR botnet. The terminology you are using ("blackhole", "mothership", "zombies", "crypto grid", etc.) makes no sense in a computer security context and is only designed to sound cool to skiddies. When you pretend to provide a list of _zombies_ to your _users_ via your _mothership_, you are actually delivering a list of _targets_ to your _bots_ using your _command & control_ server.

Moreover, you put on your website slides from a presentation at "Ninja DDoS Nation" but when googling for this, the only results that come up are related to UFONet. In the same fashion, you pretend you took part in Hackron 2018 but finding any proof that you actually did a talk at this conference seems impossible.

Anyone that asks you remotely technical question on here gets dismissed with a condescending tone and redirected to technical links that do not answer the question. How do you expect to be taken seriously ?

**Comment by epsylon** [comment]
other related trolling/hater acts from @pcouy -> https://github.com/epsylon/ufonet/issues/280#issuecomment-756120636

**Comment by pcouy** [comment]
You can call me a troll all you want, you still did not answer any of my concern. Neither did you show proof that this tool is legit. I will not go so far as to pretend I'm an expert, but for anyone willing to check my profile on root-me.org you can see I'm clearly not a troll and that I have at least some idea what I'm talking about.

In Dec 2019, after reading all you "documentation", I politely asked you, to clarify the core concept behind your tool. You did not provide any useful answer. For instance, you suggested Google was not a good search engine for my purpose, right before providing 3 links that I had already found on Google when I was trying to understand how your apparently unique way of DDoSing works. Then you wrote a sentence about hundreds of thousands of "who knows what" all going to the same site, like I am too dumb to know what "distributed" means. But you did not explain in any way how you turn an Open Redirect into any kind of ditributed attack.

I once again stumbled upon this repo today and began reading other issues, looking for any kind of technical details, but could not make sense out of any laconic explanation you are willing to provide.

> I DO know what an open redirect is : it allows me to craft a link that appears to be hosted on some domain, but when opened in a web browser redirects to another domain. The main purpose (attacker-wise) of this class of vulnerabilities is to perform phishing attacks. In no way does it make the server (that you call a "zombie") perform any request to the target.

Why did you not answer this ?

> Moreover, you put on your website slides from a presentation at "Ninja DDoS Nation" but when googling for this, the only results that come up are related to UFONet. In the same fashion, you pretend you took part in Hackron 2018 but finding any proof that you actually did a talk at this conference seems impossible.

It should be trivial for you to provide proof that you were a speaker at Hackron. Why don't you show us your badge ?

Don't pretend you don't have time to answer. You have demonstrated that you have plenty of time to be rude to anyone daring to ask you any question, as well as to make threats.

**Comment by epsylon** [comment]
@pcouy First of all, what I see is that you are not really asking questions about the software, but issuing opinions, judgments and creating confusion, so my answers are condescending and not a productive dialogue. Surely, because I have a scientific mind.

Also, as I see in your account, you just created it and you barely have 2 followers. If you have created it to carry out this type of interaction in the Community, I ask that you better come forward with your identity, in order to maintain a dialogue that is useful for the rest of the people who read us, and therefore, to obtain constructive conclusions.

It seems to me that you are wasting the time of interesting people, you are creating discredit of tools that serve the people and after all, this resource, called "fake news", is well known and is part of the society in which we live . Trust me, I don't have time for these kinds of interactions.

It is better that we talk about facts, that you point me out places in the code and stop speculating about who I am or what the tool I have created does.

For now and so that you have time to reflect, I'm going to ban you for a while.

Hugs.

**Comment by sinaj2889** [comment]
> ?

I can say it's true that he never really helps and develops the botnet to be useful and it never hits and he says I don't know how to use it I studied it i swear since a year or so and the idear of using script kiddies as your bots is a good idear but I don't think people use this tool because it's just trash and encryption doesn't even work.

**Comment by sinaj2889** [comment]
> @pcouy First of all, what I see is that you are not really asking questions about the software, but issuing opinions, judgments and creating confusion, so my answers are condescending and not a productive dialogue. Surely, because I have a scientific mind.
> 
> Also, as I see in your account, you just created it and you barely have 2 followers. If you have created it to carry out this type of interaction in the Community, I ask that you better come forward with your identity, in order to maintain a dialogue that is useful for the rest of the people who read us, and therefore, to obtain constructive conclusions.
> 
> It seems to me that you are wasting the time of interesting people, you are creating discredit of tools that serve the people and after all, this resource, called "fake news", is well known and is part of the society in which we live . Trust me, I don't have time for these kinds of interactions.
> 
> It is better that we talk about facts, that you point me out places in the code and stop speculating about who I am or what the tool I have created does.
> 
> For now and so that you have time to reflect, I'm going to ban you for a while.
> 
> Hugs.

It literally has no power and open redirect is just the server giving me the url but I would need to open it for a request the server doesn't request anything from the attacked one so either your lying or you don't have a clue how open redirect works

**Comment by sinaj2889** [comment]
@epsylon 
> Also, as I see in your account, you just created it and you barely have 2 followers. If you have created it to carry out this type of interaction in the Community, I ask that you better come forward with your identity, in order to maintain a dialogue that is useful for the rest of the people who read us, and therefore, to obtain constructive conclusions.
> 
How many followers you have doesn't tell your knowledge.

**Comment by epsylon** [comment]
related: https://github.com/epsylon/ufonet/issues/406#issuecomment-1185403021
