### ISSUE TITLE
Problem on Ubuntu

### ISSUE THREAD

**Issue by TheK0tYaRa** [epsylon/ufonet#200]
```
[Error] UFONet no longer supports Python2: (https://www.python.org/doc/sunset-python-2/)

[Info] [AI] Try to run the tool with Python3.x.y (ex: python3 ufonet)
```

This happens while running with `python3 ufonet --gui` in menus

**Comment by epsylon** [comment]
@TheK0tYaRa this happens because you didn't set Python3.x.y as an environment or an alias (ex: alias python=python3) on your box...

Probably, when you run "python --version" you will have Python2 instead of Python3. Isn't it?. 

If this happens, you should consider to --update-alternatives to use Python3 as main environment, create a virtual environment to jump when required or even remove previous Python2 installation.
