### ISSUE TITLE
Bots not connecting, other issues

### ISSUE THREAD

**Issue by Vepth** [epsylon/ufonet#204]
Hello,

Tried to use UFOnet on this new update. First thing is problem with GUI that it says:
`[Error] UFONet no longer supports Python2: (https://www.python.org/doc/sunset-python-2/)
[Info] [AI] Try to run the tool with Python3.x.y (ex: python3 ufonet)`

I saw your answer on [this issue](https://github.com/epsylon/ufonet/issues/200) but adding alias doesn't help.

Many times, I try to download zombies from community server but VORTEX FAILED

Second issue is, auto search doesn't stop so I can't get those links. I have to stop it and then use only one manual dork. When i save those restored ones and try to see if they are alive i get this error: https://pastebin.com/UucHzAB7 . Did change address after auto search so duck didn't block my new IP. Same happens with yahoo.

When I try to attack a target, in the middle and at the end of attack, program just gives errors: https://pastebin.com/B4pUczME . Also, in the program, bots attack the target but none of them actually connect to the target ( only <20 bots actually connect)

Hope you can help me.

**Comment by epsylon** [comment]
0) FAQ: https://ufonet.03c8.net/FAQ.html

1) This is related, as I have told you previously at https://github.com/epsylon/ufonet/issues/200 to your python environment configuration. Look at this video of the tool, working under Python3.7: https://ufonet.03c8.net/ufonet/ufonet-timewars.ogv

I will try to add a patch to auto-select python version (because I see that this will be a redundant "issue"). But I insists, it isn't related to the code...

2) You can try to control max number of results using: --sn=NUM_RESULTS

3) "Community Botnet" is just for testing and probably will be removed soon. People mostly is firewalled because their activity (ex: some are using ufonet website to test the botnet, others are trying their scripts, etc..) and later come here to ask me about that service, etc.. 

You (and others) have all the tools to create your own army by yourself, to share it with others, to contact with them to talk about it, etc.. Also you can try to generate your own "blackhole" to provide "zombies' and/or to connect to others. Remember that this is a P2P tool..

Btw, I will try to check/update this list provided...

**Comment by epsylon** [comment]
UFONet v1.4.1 (patch/release): https://github.com/epsylon/ufonet/commit/d19096004e99a7e9ab6f43ca584c3953828be9ac

- ADDED: auto-select PYTHON env (required for webgui)
- ADDED: exit managing for massive searching wrong replies
- ADDED: checking for valid HTTP CODE reply when testing (zombies, offline, xml-rpc, etc...)
- REMOVED: warning error "can't decode bytes" (when attacking, payloading, etc..)
- UPDATED: public "Community" botnet

**Comment by Vepth** [comment]
Thank you for the update. All working great now!
