### ISSUE TITLE
Problems downloading (my own) blackholes

### ISSUE THREAD

**Issue by Q7B** [epsylon/ufonet#215]
servers still down? if so when are they going to get back up

**Comment by epsylon** [comment]
What are you talking about @Q7B?. Let me see... 

So, you have written to me and email, telling me that your RaspBian has a segmentation fault when using UFONet and I have provided you a line for researching/debugging for that problem. I have tell you that this is mostly related to "threads" and memory resources.... 

And now you come here to what, exactly?. Are you another attentionwhore?.. What servers are down?...  I am (and with me, thousands of users more) using that servers, EVERY DAY!!!. For what do you think that you are the unique one having that problem?. Because probably, you have been firewalled due to your activity (or the ip that your are using)...

So...try to keep calm...and stay a bit of time outside our domains after the ban has expired. Ok?.And don't waste my time...
