### ISSUE TITLE
blackhole problems

### ISSUE THREAD

**Issue by dontbanmeplz** [epsylon/ufonet#233]
[Error] [AI] Not 'abductions.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'troops.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'robots.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'drones.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'reflectors.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'crystals.txt.gz' file in /var/www/ufonet/
[Error] [AI] Not 'warps.txt.gz' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'abductions' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'troops' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'robots' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'drones' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'reflectors' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'crystals' file in /var/www/ufonet/
[Error] [AI] Write access denied for 'warps' file in /var/www/ufonet/

[Error] [AI] Cannot found any container... -> [Aborting!]

[Info] [AI] Suspend [Blackhole] with: Ctrl+z

that is the error message when I run `./ufonet --blackhole` this is my first time using so I don't know what is going on.
Thanks!
Edit: I didn't give a lot of info so feel free to ask

**Comment by epsylon** [comment]
@dontbanmeplz Attention problems?. Because you are really near, here, to be banned :-D

This feature (--blackhole) is an advanced option that requires to know exactly whats going on because it requires also to NAT your router.

A good first step to use it is try to read **/docs/README_blackhole.txt** and follow the instructions -> https://github.com/epsylon/ufonet/blob/master/docs/README_blackhole.txt
