### ISSUE TITLE
Attacking a Router

### ISSUE THREAD

**Issue by SkyBoltDom** [epsylon/ufonet#235]
Hello, I have an issue with the ddos attack. When I run an attack against myself, it says my router is offline. I hping3 it and got results back. Does there have to be open ports on the router or a webpage for it to be attacked? Using http://ip/ does not seem to work with hping3 either. I am wondering if it is a syntax error or should there be a domain name? Thanks.

**Comment by SkyBoltDom** [comment]
Turns out headless mode solves this issue. I have a new problem though which is zombies do not post back and connect to me when I ping them. I have about 89 working zombies but only 3 of them are being shown on the geoip map. On the terminal, I see requests sent but am not sure if the target received any. I love your tool and you have done a great job on it. Also I want to know why only 5 zombies are being downloaded from the github. Do you know why?

**Comment by epsylon** [comment]
@SkyBoltDom 
You can check logs at server side when --attack-me to verify that zombies are reaching correctly your box. You will see their IPs. With that list you can perform other test, such as DNS, to try to debug why GeoIP isn't resolving them. You will be able to see the different IPs of the zombies that have arrived, so that, in case geolocation is a DNS problem, you can check it by modifying them. 

Do you use any proxy ?. 

It is also likely that the servers used to resolve the addresses are rejecting your requests. 

There are quite a few things and none have to do with the tool, really.

**Comment by SkyBoltDom** [comment]
yes i am aware they are do not have anything to do with the tool, but I
tried ddosing my own server with over 600 zombies, yet no effect on
connection time. The PHP redirects only send one request at a time from
each zombie so it is kind of hard to perform it successfully.

**Comment by epsylon** [comment]
@SkyBoltDom probably your bots are mostly "out-dated"... Try to search for new ones and let's UFONet to discard those that aren't working. After that, try again --attack-me option to make a more valid list.
