### ISSUE TITLE
Can't do ./ufonet --gui

### ISSUE THREAD

**Issue by teamd4rk** [epsylon/ufonet#25]
This is my command, and it's output:
./ufonet --gui
Traceback (most recent call last):
  File "./ufonet", line 16, in <module>
    app.run()
  File "/root/Desktop/ufonet-v0.8/core/main.py", line 458, in run
    self.create_web_interface()
  File "/root/Desktop/ufonet-v0.8/core/main.py", line 1077, in create_web_interface
    tcpsock.bind((host,port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

What is the fix?

**Comment by epsylon** [comment]
This is because you are trying to re-run tool and socket is still open. Did you closed it correctly before?.
You can solve it by closing socket (killing app process | ex: killall python) or waiting for it to expire...
Finally if you cannot wait, you can change gui port on code at this line:
https://github.com/epsylon/ufonet/blob/master/core/webgui.py#21

**Comment by teamd4rk** [comment]
Thank you very much for the fast reply, I changed Internet connections and this fixed. Will do your answer next time though! have a good one.
