### ISSUE TITLE
Can you add an open source liscence ?

### ISSUE THREAD

**Issue by Thecakeisgit** [epsylon/ufonet#28]
Please can you add it, so we can fork and modify it :D

**Comment by epsylon** [comment]
UFONet is entirely free software. License GPLv3: http://ufonet.03c8.net/#license

**Comment by olea** [comment]
The best practice here is to explicitly add the text of the choosen license in a separated file in the upstream source code[1]. In the case of the GNU licenses it's useful becasue explicits which variation applies: «or later version» or just the precise version[2].

The provided link is not clear enough because doesn't link to the exact license variation you wish. 

Sorry for being so annoying but Linux distros packaging guidelines requires stuff like this O:-)

[1] https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
[2] https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#.22or_later_version.22_licenses

**Comment by epsylon** [comment]
Hi,
Each file on the UFONet package starts with a short of the license. It is explicitly on code, documentation, website, etc...

This is the text you will found:

""""
UFONet - DDoS Botnet via Web Abuse - 2013/2014/2015/2016 - by psy (epsylon@riseup.net)

You should have received a copy of the GNU General Public License along
with UFONet; if not, write to the Free Software Foundation, Inc., 51
Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""

Btw, to "fix it" is just to add a file to "docs" folder. I will have it in mind for next releases.

Thanks for the suggestion. ;-)

**Comment by epsylon** [comment]
License has been added here: https://github.com/epsylon/ufonet/blob/master/docs/LICENSE
