### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by teniser1** [epsylon/ufonet#287]
this seems not to be working. I tried a simple website, first I used a simple httpflooder and it worked . Then I used ufonet but it didn't take down the small website.

**Comment by deeshirazi** [comment]
> this seems not to be working. I tried a simple website, first I used a simple httpflooder and it worked . Then I used ufonet but it didn't take down the small website.

what kind of http flooder did you used?

**Comment by epsylon** [comment]
@teniser1 to DoS (Denial Of Service) a website has multiple variables... I recommend you to sniff traffic when UFONet is working to verify that all packages are correctly sent. Also, check that your target hasn't messures to mitigate it, to have a strong botnet and to combine different attacks in order to achieve your goal.
