### ISSUE TITLE
Ip Address Appears To Be...

### ISSUE THREAD

**Issue by deeshirazi** [epsylon/ufonet#291]
guys! :)
I have tried all different sort of proxy=127.0.0.1:9050 / 8118/ sock4, socks5, HTTP, HTTPS and i have changed everything on /ect7proxychains.conf at the same time i was testing Tor! Still getting the message "ip address appears to be bla bla blah! Does this program still running on Tor browser or not? If it does what´s the solution! 

Regards

**Comment by epsylon** [comment]
@deeshirazi if you want to use an external proxy such as proxychains, after configure it, you should try something like:
**proxychains python3 ufonet** ....
But, if you want to use a proxy from your environment, you should try to configure a transparent proxy (polipo, privoxy, etc..), because you cannot use TOR directly for that.
