### ISSUE TITLE
It seems that Tor is not properly set.

### ISSUE THREAD

**Issue by Cr7mbl3** [epsylon/ufonet#299]
Using polipo proxy and tor I'm sure that these are working as
`curl -s --proxy http://127.0.0.1:8123 https://check.torproject.org/ | grep -m 1 "Congratulations" | xargs` returns `Congratulations. This browser is configured to use Tor.`

Anyways, when I run ufonet with `./ufonet --check-tor --proxy "http://127.0.0.1:8123"` it sais `It seems that Tor is not properly set.` plus my real IP. 

What am I doing wrong? Thanks in advance.

**Comment by epsylon** [comment]
@Cr7mbl3 You need to configure a transparent proxy (privoxy, polipo etc..), for this or whatever other tool. 

A transparent proxy allows you to "redirect" your traffic to the TOR layer. Because TOR by itself, without a proper configuration, cannot do that.

https://nordvpn.com/blog/transparent-proxy/
http://digitalarmedforces.org/index.php/8-linux/19-how-to-setup-tor-as-a-transparent-proxy-on-ubuntu-linux
https://vpnme.com/article/privoxy_and_tor
