### ISSUE TITLE
Cross platform?

### ISSUE THREAD

**Issue by Switch1024** [epsylon/ufonet#304]
It seems ufonet only works on Linux devices, because it needs some modules (Like resource) which aren't aviable on Windows. Is it possible to make it work on Windows devices?

**Comment by epsylon** [comment]
UFONet is built in Python3 which is a cross-platform language. You should be able to run it on different OS.
Which modules aren't available on Win32?

**Comment by Switch1024** [comment]
> UFONet is built in Python3 which is a cross-platform language. You should be able to run it on different OS.
> Which modules aren't available on Win32?

Sorry for the late reply. I had problems with nuke.py because it used a module that is not aviable on windows. the module is called "resource".

**Comment by epsylon** [comment]
@Switch1024 No problem for delay. I see...

At the moment, the quickest answer I can give you is that UFONet is not fully supported for use by Windows (because is a really complex software). Specifically, the "nuke" option uses a property of _IPTables_ (Line: https://github.com/epsylon/ufonet/blob/master/core/mods/nuke.py#L27), which cannot be used from operating systems like the one you mention.

In fact, I have looked to see if it would be possible to port the tool, for example, using the _pyinstaller_ library (even auto-py-to-exe) and there are many requirement bugs that would take a long time to solve. 

I do not rule out doing it, but right now, it is a much greater effort than a user can run a machine (even virtual) with any linux.

Those who use MacOSX encounter other problems, although it is easier to make the tool work, for example, through _macports_ and _pip_. 

I also understand that if any user, since UFONet is a free software tool, sees the need and has the technical knowledge and the time necessary to port it to Win32, it is welcome and in any case, I can help you to do it if there is a real will to do it. 

So for now, I can only tell you that the "nuke" option is not contemplated nor is it "cross-platform", as you well indicate and it can be seen reflected in the code itself in the following line: https://github.com/epsylon/ufonet/blob/master/core/main.py#L4904
