### ISSUE TITLE
Trying to add bots

### ISSUE THREAD

**Issue by g00t** [epsylon/ufonet#329]
Firstly, I just want to thank you for releasing this master piece and I truly am thankful for everything you've done. You answer all questions timely and effectively. I'm sorry for the dumb question, but im having trouble adding bots. I'm running kali linux, I waited a few hours to see maybe if this would fix things and tried again later. But it's been over 24 hours and im still having trouble adding bots. I currently only have 8 but trying to add more. I know this has something to do with IP bans but I haven't done anything suspicious or wrong for this to happen.

Im running: python3 ./ufonet --download-zombies

And the result is: 

[AI] [Control] [Blackhole] [Server] Reply: [VORTEX FAILED!]
------------

[Error] [AI] Unable to download list of [Zombies] from this [Blackhole] [Server] -> [Exiting!]

Again, I'm sorry if this is something self-explanatory or something, just having a hard time trying to fix this :)

**Comment by epsylon** [comment]
The grider has been temporarily offline ... You know, some UFONet users test the attack functions of the tool against the shared server we use to welcome newcomers and certain resources. That is why it is so important that the more experienced begin to have their own Grider up and running and available. Only then will the network we are creating be robust enough so that it does not matter if a node stops working.

The service is now operational again.
