### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by Ozymumbles1** [epsylon/ufonet#34]
Hey, I keep getting this error:

Traceback (most recent call last):
  File "./ufonet", line 14, in <module>
    options = app.create_options()
  File "/home/aaron/Desktop/ufonetlol/core/main.py", line 144, in create_options
    self.optionParser = UFONetOptions()
  File "/home/aaron/Desktop/ufonetlol/core/options.py", line 19, in __init__
    self.zombies = int(self.extract_zombies())
ValueError: invalid literal for int() with base 10: 'broken!'

Please help.

**Comment by epsylon** [comment]
It looks something wrong on your **zombies.txt** file. 
Are your bots correctly added to folder "botnet"?. 
I recommend you to re-install UFONet.

**Comment by RaNdOm0313** [comment]
Mmm... yea having the same problem. Nothing helped so far. The thing i noticed i only get that error when for example i run ufonet like this        

python example/example/ufonet/ufonet
because i'm trying to make an alias.

I have even tried putting the whole thing in the /bin folder and the same thing happens. But when i run ufonet directly  ex. python ufonet. Then it works. Is it something that im doing wrong or?

Thanks

**Comment by epsylon** [comment]
@RaNdOm0313 good point!. 
Looks that it is related with paths (so you should execute UFONet from /ufonet/ folder) without any alias...Which OS are you using?
On the other hand, maybe to have some pre-compiled packages (.deb, .rpm. etc..) to download/install it easily is a good idea. I will check it.
Thanks for your support.

**Comment by RaNdOm0313** [comment]
Yea exactly. For about a month now i have been trying to find a fix and sadly without any luck. I will be happy just to be able to use this and thank you for creating such an awesome tool.

P.S if you will include any fix to the problem just contact me.

Thanks for everything :)  👍

**Comment by epsylon** [comment]
Actually there are some pull requests (tasks) on that way (packaging), so I think it will be more easy to install/run it soon..
Thanks to you!! :8ball:
