### ISSUE TITLE
From OTHERS: NO-> [target looks OFFLINE!]

### ISSUE THREAD

**Issue by saulsmokeitall** [epsylon/ufonet#353]
Hello im really sorry to bother you guys over such a noob question but iv been struggling with this for almost 3 days and still have yet to figure it out, i keep getting this error after performing an attack, dosnt seam to matter which host is being targeted i get the same thing everytime 

"From you: yes -> [200-OK]"
"From others: no -> [target looks offline]"

The only thing i could find related to this is somone said that i have to switch my default browser from Chrome to Tor or FireFox but havnt been able to do so because im using a chromebook running linux Cent OS (about as much as i know about it off hand sorry) , i also got this other message after trying to run "Attack Me!"

"It seams that you are not using TOR to receive data"

If somone could maby help me a lil or atleast tell me weather i need to have TOR/FireFox set as my default browser or not, it would be very much appreciated i dont ask questions much especially when i have to make a post but iv been stuck on this for awhile now n dont really know anyone else that i can talk to about this kinda stuff (networking/hacking)

**Comment by epsylon** [comment]
You are welcome @saulsmokeitall 

First of all, you are mixing different things...

That is why I recommend you to report using the following template, which makes it quite easy to understand what is running, in what environment and what results we are obtaining:

https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md

1) Target tracing:

` "From others: no -> [target looks offline]"`

Is your target accessible from the external network or is it on your LAN?

Can you try entering it manually in the following online service? 

https://downforeveryoneorjustme.com/

Currently, this other service used by UFOnet to check if target is available; https://status.ws/ -> is offline!

Finally, you can bypass this check using following option:

`  --no-head           Disable 'Is target up?' starting check`

2) Option: --attack-me

This option will be used to test that the zombies act correctly, specifically, making connections to your own IP. Therefore, it is a coherent check that first sees that you are not using TOR, since it could not find you.

It requires some configuration of your NAT. I recommend that you follow the instructions that UFONet gives you as you run it until you get it to work. If not, search the Internet for how to make your IP temporarily public to be able to do the tests efficiently. 

Finally, to check that you use TOR correctly, you can use the following command: 

`--check-tor           check to see if Tor is used properly`

Regards!
