### ISSUE TITLE
Error running GUI on my Azure VPS

### ISSUE THREAD

**Issue by TheEdaL06** [epsylon/ufonet#372]
Hello, I wanted to comment on an error that happens to me when executing `python3 ./ufonet --gui`, whether or not it has **root** permissions, always returns an error above and does not execute the interface. I have tried to open the ports but it still does not work, I have looked for other problems but I have not found a solution. Here is more information about the error:

> WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6

![image](https://user-images.githubusercontent.com/31509039/152873952-4b3dd650-fd5b-4810-b474-63c8fc902233.png)

**Comment by epsylon** [comment]
Hi @TheEdaL06,

Answer this... Is your machine an only-shell server? -> (Y/n)

Because to run "--gui" you need a Web browser. Or at least, to forwarding your X11-socket to another place (ex: SSH tunneling).

Why you don't try to use UFONet directly from the shell?. 

+FAQ: https://ufonet.03c8.net/FAQ.html

+RUN: python3 ufonet --examples

On the other hand, the message that you are pointing on it, is just a "Warning", don't worry!. ;-)

It happens because you haven't IPV6 working at your system and was provided by the "tcpdump" library. You can try to configure that. 

So, your issue doesn't look directly related with UFONet.
