### ISSUE TITLE
[Error] [AI] Unable to connect to target -> [Exiting!]

### ISSUE THREAD

**Issue by Ostrichwarlock** [epsylon/ufonet#378]
What can occur this problem, can u help?

[Error] [AI] Unable to connect to target -> [Exiting!]

**Comment by epsylon** [comment]
@Ostrichwarlock How do you want me to guess what happens if you do not give me any more details?

Fill out the following template to make the task easier:

https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md

Can you access your target through the web?. It has fallen, maybe?. Is the URL well written?...

**Comment by MiChaelinzo** [comment]
Show all the code also target command is `-a http://google or http://192.168.1.1` for example. You need to add http:// or https://
