### ISSUE TITLE
Launch attack but nothing happend

### ISSUE THREAD

**Issue by QwartzNetwork** [epsylon/ufonet#394]
I have a probleme when launching attack, nothing happend on the map, it's just displayed zombies but target doesn't localised and not shown 
![image](https://user-images.githubusercontent.com/47123005/166545283-211bb638-869e-421d-bcf6-87341697acf5.png)

**Comment by QwartzNetwork** [comment]
![image](https://user-images.githubusercontent.com/47123005/166602644-6cf1cb77-75a1-4014-a4f4-c857bcde73cd.png)
 I've test the "Attack Me" option but I've got this error :(

**Comment by MiChaelinzo** [comment]
Have you tried using `python3 ufonet --test-all` ? to test working botnets & zombies
also doing `--auto-search` to have new zombies.

**Comment by QwartzNetwork** [comment]
I'll test that and I'll post feedback when it's finished

**Comment by QwartzNetwork** [comment]
I used `--auto-search` but I've got this error 
![image](https://user-images.githubusercontent.com/47123005/166712512-fdb53d3b-ea49-4a53-a961-0165ecbbbfee.png)

**Comment by QwartzNetwork** [comment]
I've tested solutions but no fix the problem :(

**Comment by QwartzNetwork** [comment]
I've follow steps to configure tor and proxychains but didn't work, zombies download work as well but attack still don't work :'(

**Comment by epsylon** [comment]
@QwartzNetwork try to report in a step by step mode, because this is a complex piece of software with many variables, some of them related to third party (out of the scope) and it is very difficult to be efficient when providing support.

1) Sometimes the geolib cannot found the IP in the Geodata.db. You should have some tips/output about this issue, if is your case, at the logs of the Map Console (right down on your screen).

2) UFONet is using some different IP external checkers:

        self.check_ip_service1 = 'https://checkip.org/' # set external check ip service 1 [OK! 06/06/2020]
        self.check_ip_service2 = 'https://whatismyip.org/' # set external check ip service 2 [OK! 06/06/2020]
        self.check_ip_service3 = 'https://ip.42.pl/ra' # set external check ip service 3 [OK! [06/06/2020]

Are these services working for you?. Do you have access to them via Web Browser?. 

From here, at the date of today are working: OK!

3) Search engines try to block dorking techniques by filtering the requests/IPs  (by the amount of them, by geolocation, by the speed of the requests, etc..). To avoid this, you can try to:

A) Change your IP (for example, reloading your TOR circuit) and repeat the task: _--auto-search_ until you have one that works
B) Try to make your request more slowly (to be more "human-like"), for example using: _--delay 15_
C) Try to use each search engine one by one. ex: _--se=duck_, _--se=yahoo_ and so on...
C) Try to exclude some of the engines when massive searching. ex: _--sax=yahoo,bing_

**Comment by QwartzNetwork** [comment]
still doesn't work :(
I quit...

**Comment by epsylon** [comment]
@QwartzNetwork to "fix" geoip issue, try this: https://ufonet.03c8.net/#installation

**sudo apt-get install python3-geoip libgeoip1 libgeoip-dev**

And to use another external IP checker, change it at code:

https://github.com/epsylon/ufonet/blob/master/core/main.py#L63

**Comment by QwartzNetwork** [comment]
> @QwartzNetwork to "fix" geoip issue, try this: https://ufonet.03c8.net/#installation
> 
> **sudo apt-get install python3-geoip libgeoip1 libgeoip-dev**
> 
> And to use another external IP checker, change it at code:
> 
> https://github.com/epsylon/ufonet/blob/master/core/main.py#L63

All is installed, I changed the external IP checker and still not working

**Comment by QwartzNetwork** [comment]
![Screenshot_20220601_112702_com server auditor ssh client](https://user-images.githubusercontent.com/47123005/171373426-0e79a6a0-153c-4612-9cbc-9808c06b1be5.jpg)

And have these errors

**Comment by QwartzNetwork** [comment]
![image](https://user-images.githubusercontent.com/47123005/171379419-f0836eaf-364a-4c7f-ac60-e3e2e3c78ff6.png)
I have this error

**Comment by epsylon** [comment]
@QwartzNetwork you are mixing, every thing that you found and think that is an "issue" on the same thread (with also have a different topic), being practically a troll :)

Btw, this last error is:
- because you have the "zombies.txt" file empty. 
- because your GeoIP lib is not resolving correctly.

**Comment by QwartzNetwork** [comment]
How to make GeoIP lib resolving correctly ?

**Comment by QwartzNetwork** [comment]
> @QwartzNetwork you are mixing, every thing that you found and think that is an "issue" on the same thread (with also have a different topic), being practically a troll :)
> 
> Btw, this last error is:
> 
> * because you have the "zombies.txt" file empty.
> * because your GeoIP lib is not resolving correctly.

How to make GeoIP lib resolving correctly ?

**Comment by epsylon** [comment]
@QwartzNetwork GeoIP lib is an external dependency. 

Check your current versions:

ventiska% apt-cache show python3-geoip
Package: python3-geoip
Source: python-geoip
Version: 1.3.2-2

ventiska% apt-cache show libgeoip1
Package: libgeoip1
Source: geoip
Version: 1.6.12-1

ventiska% apt-cache show libgeoip-dev
Package: libgeoip-dev
Source: geoip
Version: 1.6.12-1
