### ISSUE TITLE
Pull request to github blackhole zombies

### ISSUE THREAD

**Issue by MiChaelinzo** [epsylon/ufonet#395]
I'm planning to upload in blackhole but I couldn't connect I want to pull request to upload here in Github, how do I do that?

**Comment by epsylon** [comment]
Hi @MiChaelinzo 

First of all, it is important that you know that this function is implemented in case the UFONET tool is threatened, for example, by censorship. Or in the event that the community server was totally disabled, or that there are no nodes of other "Ufo-Masters available (it is not the current case). That is, it is an option that we have in case.

In fact, it is interesting not to upload the "zombies" here, because they are visible and can stop being useful. In addition to that Github can make decisions about it and we are not interested in giving them that power. Do you understand?

You have other more interesting routes, from uploading your "zombies" to the community server, through:-Suppload-Zombies

Or to other servers that are available, through: -Up -to = Upip

You can also display your own node with: ``

In this case and if you want to make a contribution through that path, the steps to follow are the following:

A) **python3 ufonet --upload-github** (if you have credentials on the repository)

B) If you want to upload them on a third party repository:
1) Try to _--test-all_ your zombies first, to be sure that are working
2) Make a pull request here, so Community can check them
3) Profit! ;-)
