### ISSUE TITLE
unable to conect to duckduckgo

### ISSUE THREAD

**Issue by Jonas637** [epsylon/ufonet#401]
any search for zombies doesn't work with duckduckgo and I get the message.
[Error] [AI] Unable to connect to: duck

I don't mind if I don't get a way to fix it as Bing and Yahoo both work well but I thought id point it out to see if I'm the only one.

Also want to note I'm running kali on VMware Workstation 16 Player with windows 11 as the host OS so it may also be a problem regarding that rather than the code.

Many thanks

**Comment by AnonymousModz420** [comment]
i get the same issue on Termux i always just stop the search an start it again wherever i left off so ur not the only 1

**Comment by epsylon** [comment]
@Jonas637 @AnonymousModz420 Are you using TOR?

_We have detected that you have connected over Tor. There appears to be an issue with the Tor Exit Node you are currently using. Please recreate your Tor circuit or restart your Tor browser in order to fix this. Alternatively DuckDuckGo is available on Tor via our Onion URL: https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/. If this error persists, please let us know: error-lite-tor@duckduckgo.com_

**Comment by Jonas637** [comment]
Hi, sorry for not replying sooner I was on holiday and only just got back, iv tried with a tor network (using a transparent proxy) and without

**Comment by sinaj2889** [comment]
Same thing as @AnonymousModz420

**Comment by AnonymousModz420** [comment]
they said running tool through tor is what causes this to happen i just stop search and sart it back up where i left off
