### ISSUE TITLE
main.py will cause errors when scraping

### ISSUE THREAD

**Issue by ghost** [epsylon/ufonet#405]
### 1
https://checkip.org/ is
`<h1>Your IP Address:  <span style="color: #5d9bD3;">180.4.14.196</span></h1>`
so main.py:4035 must be
`self.pub_ip = re.compile(r'(\d+\.\d+\.\d+\.\d+)').search(data).group(1)`
### 2
main.py:4034 and main.py:4039
`data = str(urlopen(self.check_ip_service1).read()) # check for public ip`
must be
`data = str(urllib.request.urlopen(self.check_ip_service1).read()) # check for public ip`
<hr>
Probabry.

**Comment by darkestscience** [comment]
I tried those pattern.
![scs3](https://user-images.githubusercontent.com/108727137/178438360-a9dba242-6c36-47fb-9b9c-66c2860b3efc.png)
![scs2](https://user-images.githubusercontent.com/108727137/178438367-89df9179-97d5-4187-b47b-c9b0ba8c0aee.png)
![scs](https://user-images.githubusercontent.com/108727137/178438371-f0ce3ea8-b85b-4a7d-9cae-944ebd11d76a.png)
Of the three patterns, only the one incorporating the top two improvements was marked as SUCCESS.

**Comment by epsylon** [comment]
@darkestscience I don't understand where you want to get there. Do not regular expressions work as they are?

**Comment by epsylon** [comment]
External checker -> https://status.ws/  -> is down... but the tool should try the next one, which is actually working

**Comment by darkestscience** [comment]
<h1>working services</h1>
check_ip_service1 = 'https://checkip.org/' 
check_ip_service3 ='https://ip.42.pl/ra'
these are working.
but
check_ip_service2 = 'https://whatismyip.org/'
returns 403
when request from python code.
<h1>Sentence error</h1>
ERRO: name 'urlopen' is not defined↓
<pre><code>import urllib.request, urllib.error, urllib.parse
str(urlopen(check_ip_service1).read())</code></pre>
fix
<pre><code>import urllib.request, urllib.error, urllib.parse
from urllib.request import urlopen
str(urlopen(check_ip_service1).read())</code></pre>
<h1>regular expressions</h1>
'NoneType' object has no attribute 'group' error because search result is none ↓
<pre><code>re.compile(r'Address: (\d+\.\d+\.\d+\.\d+)').search(data).group(1)</code></pre>
fix(change)
<pre><code>pub_ip = re.compile(r'(\d+\.\d+\.\d+\.\d+)').search(data).group(1)</code></pre>

**Comment by epsylon** [comment]
@darkestscience Sorry but I don't see your point... Do not regular expressions work as they are or you are providing another code for other reasons?

**Comment by epsylon** [comment]
@darkestscience Ok, you're referring to the "--attack-me" option.

It should work after this commit: https://github.com/epsylon/ufonet/commit/753904e3923c9d972997ff7b060acce38c3801f9

Thanks for your time! ;-)
