### ISSUE TITLE
doesn't work anymore 

### ISSUE THREAD

**Issue by Rsv002** [epsylon/ufonet#431]
i can ddos a website with only a machine but i can't ddos it with ufonet.

**Comment by tsimon05** [comment]
did it work before tho?

**Comment by epsylon** [comment]
What do we have here? 

A small troll convention with accounts created reciently and that they come to talk badly about the tool. Maybe because you have copied the code and want your pathetic tools to be used?  ;-)

UFONet works perfectly. The only thing, which requires using some time to configure it and have a competent botnet. Defense methods have been sophisticated and it is no longer like years ago (remember that UFONet has been a pioneer on DDoSing) and therefore, some time must be used to understand and configure it well.

It also depends on the target. There are targets that are housed behind the balancers and network firewalls (NIFS, etc), and it is also convenient to study the objective to know the possibilities.

Get more time to study the code and look at how network packages are sent and less to come here to show that you are newbies/wannabies. :-)

The source code does not deceive.

**Comment by tsimon05** [comment]
why you so mad lol

**Comment by epsylon** [comment]
@iloveyumyumshrimpnoodles <-> joined 2 weeks ago ...

When I mean pioneer, I don't talk about the whole tool, no doubt. But there are some parts in which a gap opened.

In 2013, when the first stable version of the tool came out, the idea of using validators as an Open Redirect (CWE-601), had never been exploited in this way. 

A way in which also, just making a single request, no crime is either committed against "zombies". Even bothering or degrading their service. UFONet was opening a way for mass digital activism, much more sophisticated than LoIC. It allowed individual attacks and with more people or not (DoS, DDoS & mDDoS). 

For the first time the grayhats could continue to maintain their ethic in the electronic protest, without having to depend on the blackhats. A new era of hacktivism had just been born.

On the other side of the currency you had botnets, usually of closed code and many payment (most of them with backdoors). UFONet served as an alternative for free software, which also allowed academic and fans (no only blackhats), to understand a DDoS, but also to practice it.

UFONet also serves to answer those who say: "Denial Of Service is not hacking". -> "You're sure?". "It is not easy to sneak something effective and that invalidates the hundreds of existing security measures".

I think you are not very fair with your words. Or your need to attack a tool, surely because you are interested that only shows that it is always easier to speak on the Internet from your position, than that of independent developer.

Anyway, check the v0.1 (2011) version code and try to search the initial plan. There are other points in which UFONet is a pioneer and maybe you even want to be yourself who puts them, this time.

;-)

**Comment by iloveyumyumshrimpnoodles** [comment]
> @iloveyumyumshrimpnoodles <-> joined 2 weeks ago ...
Why does it matter that i only joined 2 weeks ago. Would my statement be any different if i joined 7 years ago?

> In 2013, when the first stable version of the tool came out, the idea of using validators as an Open Redirect (CWE-601), had never been exploited in this way.
Trust me, it had. Perhaps with a tool that never got as much publicity as yours but it definitly has been (ab)used. Just because your tool got known and the others didn't doesn't mean you can go and claim all the credits.

> A new era of hacktivism had just been born.
AFAIK i've never seen UFONet being used as much as LOIC or HOIC, sooo wdym with "a new era"?

As a fellow dev; i do respect you for being able to deal with the amount of idiots who can barely run a python script, that isn't an easy thing to do.

But yeah, since internet arguments tend to go nowhere i'll just end this conversation. Have a good day/night
