### ISSUE TITLE
Why everything is down even though the website is up???

### ISSUE THREAD

**Issue by MiChaelinzo** [epsylon/ufonet#455]
```
[AI] Launching: 'Is target up?' check...

[Info] [AI] [Control] From YOU: NO -> [Target looks OFFLINE!]

[Info] [AI] https://cisa.gov -> [Target looks OFFLINE!]

---------------------

[AI] Generating random exit... 

 -> No pasarán!

```
having this problem for several weeks now!

**Comment by trntyy** [comment]
> ```
> [AI] Launching: 'Is target up?' check...
> 
> [Info] [AI] [Control] From YOU: NO -> [Target looks OFFLINE!]
> 
> [Info] [AI] https://cisa.gov -> [Target looks OFFLINE!]
> 
> ---------------------
> 
> [AI] Generating random exit... 
> 
>  -> No pasarán!
> ```
> 
> having this problem for several weeks now!

Months ago when I could run this tool, the server never went down, that is, it never closed.
I even tested with bad servers and it didn't work. It's strange, maybe this tool doesn't work. Right now I can't run it because I get logintrepr.h errors. I recommend using slowhttptest, it is a thousand times better and it does close the servers.
