### ISSUE TITLE
*** longjmp causes uninitialized stack frame ***: /usr/bin/python2.7 terminated

### ISSUE THREAD

**Issue by knightgats** [epsylon/ufonet#6]
Gentoo AMD64 Stable - dev-lang/python-2.7.10-r1:2.7

http://codepad.org/EamqpxQt

Also, there is the same error when trying to use dorks google and other sites not working properly

If you need anything to test , let me know, I`ll help you

Thanks

**Comment by epsylon** [comment]
I think that it is a problem with a bug on libcurl. Which version do you have?.

"libcurl built without an asynchronous resolver library uses alarm() to time out DNS lookups. When a timeout occurs, this causes libcurl to jump from the signal handler back into the library with a sigsetjmp, which effectively causes libcurl to continue running within the signal handler."

Try this fix on machine that is not working: 
      - add to file: /core/zombie.py after Line: 94 this code:
               c.setopt(pycurl.NOSIGNAL, 1) # pass 'long' to stack to fix libcurl bug
 If all is ok, you shouldn't have more that error. Please try it and feedback results. If is working I will supply a commit for it.

Thanks for your time and your report.

Kisses.

**Comment by knightgats** [comment]
Works like a charm ! 
c.setopt(pycurl.NOSIGNAL, 1) # pass 'long' to stack to fix libcurl bug

:dancers: 

Count on me ! 

As said Duke Nukem ( Let`s rock !!! )

**Comment by knightgats** [comment]
dev-python/pycurl
      Latest version available: 7.19.3.1-r2


 net-misc/curl
      Latest version available: 7.45.0

**Comment by knightgats** [comment]
some times engines ( google etc )  works other no, it`s a little unstable

**Comment by epsylon** [comment]
Is that last comment related with this bug?..

If not, take this trick: google (and some others) is trying to block Tor network connections providing a captcha to be resolved when website visit. Because of UFONet cannot resolve that question from network layer, google is blocking connections after you change your IP:

You can try to restart your Tor network relay to try to found a non-blocked IP, using for example: /etc/init.d/tor restart

Or you can visit google with this IP, solve captcha manually and try UFONet again. This last version will be more agradable for rest of Tor community...

**Comment by knightgats** [comment]
can we talk on #ufonet ?

**Comment by knightgats** [comment]
I`m on  $ufonet ping me there

The issue related with libcurl already fixed with 
c.setopt(pycurl.NOSIGNAL, 1) # pass 'long' to stack to fix libcurl bug

feel free to resolve this issue
