### ISSUE TITLE
[Error] - Something wrong searching using: yahoo

### ISSUE THREAD

**Issue by emiann12** [epsylon/ufonet#64]
I saw another issue thread and it worked fine and it didn't stop the searching of the zombies, but when it was done searching for the zombies it asked if I wanna check if they were valid I wrore y for yes and it just came this message "[Error] - Something wrong searching using: yahoo" and I never received my bots 

Any help is appreciated :D

**Comment by emiann12** [comment]
Now I think it worked still popped up but it managed to keep going but how to I add the zombies to the botnet? They were never added and every time I try again they are still not added.

**Comment by epsylon** [comment]
hey @emiann12

UFONet is using a special mechanism for Yahoo dorking that works with a different location server each time of executing, to try to evade some search engine restrictions. 

You can see which server are you using like exit node by adding -v (verbose) to your command. 

Sometimes works and sometimes not, just because is using different routes.

Btw, I have reviewed Yahoo dorking again and I have made some changes to fix your request: https://github.com/epsylon/ufonet/commit/f912580b814cf264654bb090e7c25fdfc37c9421

Thanks for your report.
