### ISSUE TITLE
[Error] - Something wrong downloading! Not a gzipped file

### ISSUE THREAD

**Issue by DarkGohst** [epsylon/ufonet#71]
Sry that i bother you but i get ervery time i want to dowload this error
[Error] - Something wrong downloading!
Not a gzipped file

**Comment by epsylon** [comment]
This happens when you cannot reach a "blackhole" correctly. 

Maybe because your IP is banned on server side, your proxy is blocking requests or just simply because your network connection is not working. 

You should see when starting a transfer a STATUS tag, that try to notice you if the server is: OK.

If you are trying Community "blackhole", right now (tested) it is working perfectly.
